### ISSUE TITLE
ViT-L-14--laion400m_e32 Error

### ISSUE THREAD

**Issue by putuoka** [dmarx/Multi-Modal-Comparators#40]
unexpected EOF, expected 6371631 more bytes. The file might be corrupted.

**Comment by dmarx** [comment]
hmm... well that's no good. will look into this, thanks!

**Comment by putuoka** [comment]
Sorry it seem like the connection make it corrupt. it actually work now

**Comment by dmarx** [comment]
lol glad to hear you're unblocked, let me know if you experience any other issues :)

**Comment by putuoka** [comment]
alright i got an error in [cloob - crowsonkb - cloob_laion_400m_vit_b_16_32_epochs]

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>
